server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti-demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    password: 199815
    username: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level: debug

  spring:
    activiti:
        database-schema-update: true
       #启动时默认不加载流程配置文件
        check-process-definitions: true
        process-definition-location-prefix: classpath:/processes/